### ISSUE TITLE
Deployment failing due to outdated node version

### ISSUE THREAD

**Issue by diverent2** [diverent2/flagfinder#38]
# 🐞 bug report

## Current behavior 👎

https://zeit.co/diverent2/flagfinder/it0vj92v0
```
This project is using a discontinued version of Node.js (8.10.x) and must be upgraded.
--
10:19:00 PM | Please set "engines": { "node": "12.x" } in your `package.json` file to upgrade to Node.js 12.
10:19:00 PM | This change is the result of a decision made by an upstream infrastructure provider (AWS).
10:19:00 PM | Read more: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

```
## Expected behavior 👍

Deployment works

## Steps to fix

- [ ] Set project's node-version
- [ ] Update Test-Environments (github actions)

**Comment by DanielRuf** [comment]
Node 10 is still supported in general and did not yet reach its EOL. See https://github.com/nodejs/Release

**Comment by DanielRuf** [comment]
It seems this is a constraint by zeit.co.

**Comment by DanielRuf** [comment]
Caused by the now CLI as it seems.

You may have to check which Node.js version it uses.

https://github.com/zeit/now/blob/f65b7ec5467f9cc79ec52b7f044cd5649a5fff04/packages/now-build-utils/src/fs/node-version.ts#L71

https://github.com/zeit/now/issues/3510#issuecomment-571414975

`"node": ">=10"` should work.
